# Minimal Mistakes — GitHub Pages (remote theme)
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

remote_theme: mmistakes/minimal-mistakes@4.26.2
minimal_mistakes_skin: "mint"

locale: "en-US"
title: "Tamara's GitHub Pages"
title_separator: "-"
subtitle: "Research work, learnings and thoughts"
name: "Tamara Atanasoska"
description: "A place to publish research work, learnings and thoughts."
url: "https://tamaraatanasoska.github.io"
baseurl: ""
repository: "TamaraAtanasoska/TamaraAtanasoska.github.io"

author:
  name: "Tamara Atanasoska"
  bio: "Software engineer, OSS maintainer, researcher and PhD candidate."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tamaraatanasoska"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tamaraatanasoska/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tamaraatanasoska"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tamaraatanasoska/"

include:
  - _pages

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
